channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.12.13
  - pandas[version=">=2.2,<3"]
  - conda-forge::scanpy
  - conda-forge::squidpy
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.4
  - pip:
    - scvi-tools==1.4.2
    - latch==2.69.1